kind: pipeline
type: docker
name: dotnetpipeline

trigger:
  event:
    - push

steps:
  - name: docker-test-build
    image: plugins/docker
    settings:
       dockerfile: Sources/Dockerfile
       context: Sources/
       username:
         phopho_instant_hack
       password:
         michelinLesBests2023





